### ISSUE TITLE
Run Robot

### ISSUE THREAD

**Issue by QuietAko** [Vibof/HorizonSideRobots.jl#2]
Hello
I try to run this code on my macbook M1 and window with animation just close instantly

using HorizonSideRobots

r = Robot(animate = true)

**Comment by Vibof** [comment]
Hello!

I know that

     r = Robot (animate = true)

OS MAC may have a problem with the use of the MATPLOTLIIB graphics library (PyPlot.jl).
 
I do not have experience in Mac, but information on how to cope with this problem, apparently, can be found here:

https://github.com/JuliaPy/PyPlot.jl
https://matplotlib.org/stable/faq/installing_faq.html
https://www.macports.org/install.php.
>Суббота, 11 сентября 2021, 13:49 +03:00 от Alexander ***@***.***>:
> 
> 
>Hello
>I try to run this code on my macbook M1 and window with animation just close instantly
>using HorizonSideRobots
>r = Robot(animate = true)
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .  
 
 
--
С уважением, Фёдоров Виктор Борисович
